- name: Install required packages
  apt:
    name:
      - lshw
    state: present
  become: true

- name: Gather GPU information
  shell: lshw -C display | grep vendor
  register: gpu_vendor

- name: Install NVIDIA Vulkan drivers
  apt:
    name:
      - nvidia-driver-510
      - libvulkan1
    state: present
  when: "'NVIDIA' in gpu_vendor.stdout"
  become: true

- name: Install AMD Vulkan drivers
  apt:
    name:
      - mesa-vulkan-drivers
      - libvulkan1
    state: present
  when: "'AMD' in gpu_vendor.stdout"
  become: true

- name: Install Intel Vulkan drivers
  apt:
    name:
      - mesa-vulkan-drivers
      - libvulkan1
    state: present
  when: "'Intel' in gpu_vendor.stdout"
  become: true

- name: Install Vulkan drivers for VMware
  apt:
    name:
      - mesa-vulkan-drivers
      - libvulkan1
    state: present
  when: "'VMware' in gpu_vendor.stdout"
  become: true

- name: Install Vulkan tools
  apt:
    name:
      - vulkan-tools
    state: present
  become: true

- name: Install required packages
  apt:
    name:
      - gnupg2
      - software-properties-common
    state: present
  become: true

- name: Add LunarG repository key
  apt_key:
    url: https://packages.lunarg.com/lunarg-signing-key-pub.asc

- name: Add LunarG repository
  apt_repository:
    repo: deb https://packages.lunarg.com/vulkan/{{ ansible_distribution_release }} main
    state: present
    filename: lunarg-vulkan

- name: Update apt cache and install Vulkan SDK
  apt:
    name:
      - vulkan-sdk
    update_cache: true
    state: present
  become: true