- name: Install rustup
  shell: |
    curl https://sh.rustup.rs -sSf | sh
    source $HOME/.cargo/env
  environment:
    PATH: "{{ ansible_env.PATH }}:/root/.cargo/bin"

- name: Add rustup to PATH
  lineinfile:
    path: /etc/environment
    line: 'PATH="/root/.cargo/bin:$PATH"'
  notify:
    - source environment file
