- name: Download rustup installer
  command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

- name: Add rustup to PATH
  lineinfile:
    path: /etc/environment
    line: 'PATH="/root/.cargo/bin:$PATH"'
  notify:
    - source environment file