---

- hosts: localhost
  become: true
  pre_tasks:
  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: copy ansible host file
    tags: always
    copy:
      src: hosts
      dest: /etc/ansible/hosts

- hosts: localhost
  become: true
  roles:
    - system
    - helm
    - java
    - docker
    - kubernetes
#    - crossplane
    - vagrant
    - kafka
    - cassandra
    - postgresql
    - intellij
    - clion
#    - rust
    - linuxtools