- name: Download IntelliJ IDEA Ultimate Edition
  get_url:
    url: https://download.jetbrains.com/idea/ideaIU-{{ intellij_version }}.tar.gz
    dest: /tmp/ideaIU-{{ intellij_version }}.tar.gz
  register: download_result

- name: Extract IntelliJ IDEA Ultimate Edition
  unarchive:
    src: /tmp/ideaIU-{{ intellij_version }}.tar.gz
    dest: /opt/
    remote_src: yes
  when: download_result is changed

- name: Create a symbolic link
  file:
    src: /opt/idea-IU-{{ intellij_build }}
    dest: /opt/intellij
    state: link

- name: Create a desktop shortcut
  copy:
    src: intellij.desktop
    dest: /usr/share/applications/intellij.desktop