- name: Download IntelliJ IDEA Community Edition
  get_url:
    url: https://download.jetbrains.com/idea/ideaIC-{{ intellij_version }}.tar.gz
    dest: /tmp/ideaIC-{{ intellij_version }}.tar.gz
  register: download_result

- name: Extract IntelliJ IDEA Community Edition
  unarchive:
    src: /tmp/ideaIC-{{ intellij_version }}.tar.gz
    dest: /opt/
    remote_src: yes
  when: download_result is changed

- name: Create a symbolic link
  file:
    src: /opt/idea-IC-{{ intellij_build }}
    dest: /opt/intellij
    state: link

- name: Create a desktop shortcut
  copy:
    src: intellij.desktop
    dest: /usr/share/applications/intellij.desktop