- name: install base packages
  apt:
    name:
      - htop
      - tmux
      - vim
      - vim-nox
      - python3-psutil
      - virtualbox
      - firewalld
      - net-tools
      - golang-go
    state: latest
    update_cache: true

- name: copy wallpaper file
  copy:
    src: terraform.png
    dest: /usr/share/backgrounds/wallpaper.png
    owner: root
    group: root

- name: set wallpaper
  become_user: all
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/wallpaper.png'"

- name: set wallpaper position
  become_user: all
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'centered'"

- name: copy .bashrc file
  copy:
    src: .bashrc
    dest: /home/yahya/.bashrc
    owner: yahya
    group: yahya

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Set blank screen timeout for GNOME
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.session idle-delay 1800
  when: "'gnome' in ansible_facts['desktop']"
  become_user: "{{ ansible_user }}"

- name: Set the hostname
  hostname:
    name: "ubuntu"
  become: true

- name: Add localhost and hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: '127.0.1.1       localhost ubuntu'
    state: present
  become: true

