- name: Stop and disable whoopsie service
  ansible.builtin.systemd:
    name: whoopsie
    state: stopped
    enabled: no
  become: true

- name: Disable apport error reporting
  ansible.builtin.replace:
    path: /etc/default/apport
    regexp: '^(enabled=)1'
    replace: '\g<1>0'
  become: true