- name: Download CLion
  get_url:
    url: https://download.jetbrains.com/cpp/CLion-{{ clion_version }}.tar.gz
    dest: /tmp/CLion-{{ clion_version }}.tar.gz
  register: download_result

- name: Extract CLion
  unarchive:
    src: /tmp/CLion-{{ clion_version }}.tar.gz
    dest: /opt/
    remote_src: yes
  when: download_result is changed

- name: Create a symbolic link
  file:
    src: /opt/clion-{{ clion_version }}
    dest: /opt/clion
    state: link

- name: Create a desktop shortcut
  copy:
    src: clion.desktop
    dest: /usr/share/applications/clion.desktop