---
- hosts: localhost
  connection: local
  become: true
  collections:
    - kubernetes.core

  tasks:
    #    - name: start minikube
    #      command: minikube start

    - name: Create crossplane namespace
      command: kubectl create namespace crossplane-system


#    - name: Create Crossplane namespace
#      k8s:
#        api_version: v1
#        kind: Namespace
#        name: crossplane-system
#        state: present

    - name: Add a repository
      kubernetes.core.helm_repository:
        name: stable
        repo_url: https://kubernetes.github.io/ingress-nginx


    - name: Add helm repo for crossplane
      kubernetes.core.helm_repository:
        name: crossplane-stable
        repo_url: https://charts.crossplane.io/stable
#
#    - name: Update apt and install crossplane packages
#      kubernetes.core.helm:
#        name: crossplane
#        chart_ref: crossplane-stable/crossplane
#        namespace: crossplane-system
#        state: present
#        update_repo_cache: true
