---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Add Helm GPG apt Key
      apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: Add Helm Repository
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm-stable-debian

    - name: Update apt and install helm packages
      apt:
        name:
          - apt-transport-https
          - helm
        state: latest
        update_cache: true