---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Download Kafka
      get_url:
        url: https://downloads.apache.org/kafka/3.3.2/kafka_2.13-3.3.2.tgz
        dest: /tmp/kafka_2.13-3.3.2.tgz
        mode: 0755

    - name: Extract Kafka
      unarchive:
        src: /tmp/kafka_2.13-3.3.2.tgz
        dest: /opt
        remote_src: yes
        mode: 0755

#    - name: copy server.properties file
#      replace:
#        src: /home/yahya/ansible_desktop/files/server.properties
#        dest: /opt/kafka_2.13-3.3.2/config/server.properties
#        owner: yahya
#        group: yahya
#
#    - name: copy zookeeper.properties file
#      replace:
#        src: /home/yahya/ansible_desktop/files/zookeeper.properties
#        dest: /opt/kafka_2.13-3.3.2/config/zookeeper.properties
#        owner: yahya
#        group: yahya

#    - name: Start zookeeper
#      shell: /opt/kafka_2.13-3.3.2/bin/zookeeper-server-start.sh -daemon /opt/kafka_2.13-3.3.2/config/zookeeper.properties
#
#    - name: Start kafka
#      shell: /opt/kafka_2.13-3.3.2/bin/kafka-server-start.sh -daemon /opt/kafka_2.13-3.3.2/config/server.properties