- name: Create Crossplane namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: crossplane-system
    state: present

- name: Add helm repo for crossplane
  kubernetes.core.helm_repository:
    name: crossplane-stable
    repo_url: https://charts.crossplane.io/stable

- name: Update apt and install crossplane packages
  kubernetes.core.helm:
    name: crossplane
    chart_ref: crossplane-stable/crossplane
    namespace: crossplane-system
    state: present
    update_repo_cache: true

- name: Create crossplane namespace
  command: kubectl create namespace crossplane-system

- name: Add helm repo for crossplane
  command: helm repo add crossplane-stable https://charts.crossplane.io/stable

- name: Update helm repo
  command: helm repo update

- name: Install Crossplane
  command: helm install crossplane --namespace crossplane-system crossplane-stable/crossplane

- name: Install Crossplane CLI
  command: curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh

- name: Install GCP config
  command: kubectl crossplane install configuration registry.upbound.io/xp/getting-started-with-gcp:v1.10.2